//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZZT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MZZT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkForces_Icon16 {
            get {
                object obj = ResourceManager.GetObject("DarkForces_Icon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkForces_Icon32 {
            get {
                object obj = ResourceManager.GetObject("DarkForces_Icon32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Dark Forces.
        /// </summary>
        internal static string DarkForces_MnemonicName {
            get {
                return ResourceManager.GetString("DarkForces_MnemonicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Forces.
        /// </summary>
        internal static string DarkForces_Name {
            get {
                return ResourceManager.GetString("DarkForces_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JediAcademy_Icon16 {
            get {
                object obj = ResourceManager.GetObject("JediAcademy_Icon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JediAcademy_Icon32 {
            get {
                object obj = ResourceManager.GetObject("JediAcademy_Icon32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedi &amp;Academy.
        /// </summary>
        internal static string JediAcademy_MnemonicName {
            get {
                return ResourceManager.GetString("JediAcademy_MnemonicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedi Academy.
        /// </summary>
        internal static string JediAcademy_Name {
            get {
                return ResourceManager.GetString("JediAcademy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JediKnight_Icon16 {
            get {
                object obj = ResourceManager.GetObject("JediKnight_Icon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JediKnight_Icon32 {
            get {
                object obj = ResourceManager.GetObject("JediKnight_Icon32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Jedi Knight.
        /// </summary>
        internal static string JediKnight_MnemonicName {
            get {
                return ResourceManager.GetString("JediKnight_MnemonicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedi Knight.
        /// </summary>
        internal static string JediKnight_Name {
            get {
                return ResourceManager.GetString("JediKnight_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JediOutcast_Icon16 {
            get {
                object obj = ResourceManager.GetObject("JediOutcast_Icon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JediOutcast_Icon32 {
            get {
                object obj = ResourceManager.GetObject("JediOutcast_Icon32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedi &amp;Outcast.
        /// </summary>
        internal static string JediOutcast_MnemonicName {
            get {
                return ResourceManager.GetString("JediOutcast_MnemonicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedi Outcast.
        /// </summary>
        internal static string JediOutcast_Name {
            get {
                return ResourceManager.GetString("JediOutcast_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Knight {
            get {
                object obj = ResourceManager.GetObject("Knight", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap massassi {
            get {
                object obj = ResourceManager.GetObject("massassi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Material_Symbols_Filled {
            get {
                object obj = ResourceManager.GetObject("Material_Symbols_Filled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mods_defaults {
            get {
                object obj = ResourceManager.GetObject("mods_defaults", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MysteriesOfTheSith_Icon16 {
            get {
                object obj = ResourceManager.GetObject("MysteriesOfTheSith_Icon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MysteriesOfTheSith_Icon32 {
            get {
                object obj = ResourceManager.GetObject("MysteriesOfTheSith_Icon32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Mysteries of the Sith.
        /// </summary>
        internal static string MysteriesOfTheSith_MnemonicName {
            get {
                return ResourceManager.GetString("MysteriesOfTheSith_MnemonicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mysteries of the Sith.
        /// </summary>
        internal static string MysteriesOfTheSith_Name {
            get {
                return ResourceManager.GetString("MysteriesOfTheSith_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] patches_defaults {
            get {
                object obj = ResourceManager.GetObject("patches_defaults", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap site_df21 {
            get {
                object obj = ResourceManager.GetObject("site_df21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap site_jkhub {
            get {
                object obj = ResourceManager.GetObject("site_jkhub", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
