'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_df_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_df_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_df_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_df_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_ja_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_ja_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_ja_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_ja_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_jk_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_jk_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_jk_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_jk_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_jo_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_jo_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_jo_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_jo_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_mots_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_mots_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_mots_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_mots_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;hashes xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; algorithm=&quot;System.Security.Cryptography.SHA1Managed&quot; xmlns=&quot;mzzt:hashlist&quot;&gt;
        '''  &lt;hash datasize=&quot;1387520&quot; filename=&quot;jk.1.0.exe&quot; id=&quot;jk100&quot; name=&quot;Jedi Knight 1.0&quot;&gt;TlbtpHsfy2f5gsPMcI3L0D0HfMc=&lt;/hash&gt;
        '''  &lt;hash datasize=&quot;1388544&quot; filename=&quot;jk.1.01.exe&quot; id=&quot;jk101&quot; name=&quot;Jedi Knight 1.01&quot;&gt;FQQhLmG12LOyhexbPwfX2G87k44=&lt;/hash&gt;
        '''  &lt;hash datasize=&quot;1737728&quot; filename=&quot;jk.Steam. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property hashlist_defaults() As String
            Get
                Return ResourceManager.GetString("hashlist_defaults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property hourglass() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("hourglass", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property knight() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("knight", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;games xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;mzzt:knight:modinfocache&quot;&gt;
        '''  &lt;game name=&quot;Dark Forces&quot;&gt;
        '''    &lt;modtype type=&quot;MZZT.Knight.Games.DarkForcesModInfo&quot;&gt;
        '''      &lt;mod uid=&quot;1RMWNDR&quot; name=&quot;DarthDoctor&apos;s &amp;quot;One Room Wonder&amp;quot;&quot; xmlns=&quot;&quot; /&gt;
        '''    &lt;/modtype&gt;
        '''    &lt;modtype type=&quot;MZZT.Knight.Games.DarkForcesModInfo&quot;&gt;
        '''      &lt;mod uid=&quot;3DMAD&quot; name=&quot;3D-Mad&quot; xmlns=&quot;&quot; /&gt;
        '''    &lt;/modtype&gt;
        '''    &lt;modtype type [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property modinfocache_defaults() As String
            Get
                Return ResourceManager.GetString("modinfocache_defaults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;options xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;mzzt:knight:options&quot;&gt;
        '''  &lt;option name=&quot;BigIconsSize_Height&quot; xmlns=&quot;mzzt:options&quot;&gt;
        '''    &lt;value xsi:type=&quot;xsd:int&quot;&gt;91&lt;/value&gt;
        '''  &lt;/option&gt;
        '''  &lt;option name=&quot;BigIconsSize_Width&quot; xmlns=&quot;mzzt:options&quot;&gt;
        '''    &lt;value xsi:type=&quot;xsd:int&quot;&gt;91&lt;/value&gt;
        '''  &lt;/option&gt;
        '''  &lt;option name=&quot;DarkForcesAutoTest&quot; xmlns=&quot;mzzt:options&quot;&gt;
        '''    &lt;value xsi:type=&quot;xsd:boolean&quot;&gt;false&lt;/value [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property options_defaults() As String
            Get
                Return ResourceManager.GetString("options_defaults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_application() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_application", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_application_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_application_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_application_form_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_application_form_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_application_lightning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_application_lightning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_application_put() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_application_put", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_application_split() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_application_split", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_application_view_icons() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_application_view_icons", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_application_view_list() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_application_view_list", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_arrow_refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_arrow_refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_clock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_clock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_cog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_cog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_comments() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_comments", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_controller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_controller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_cross() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_cross", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_disk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_disk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_door_in() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_door_in", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_email_link() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_email_link", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_exclamation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_exclamation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_folder_explore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_folder_explore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_group() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_group", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_group_go() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_group_go", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_music() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_music", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_resultset_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_resultset_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_shield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_shield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_textfield_rename() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_textfield_rename", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_tick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_tick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_world() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_world", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_world_link() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_world_link", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silk_wrench() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silk_wrench", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property site_df21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("site_df21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property site_jkhub() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("site_jkhub", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property site_massassi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("site_massassi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
